/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteDirectoryRouteRouteImport } from './routes/_site/directory/route'
import { Route as SiteDownloadsRouteImport } from './routes/_site/downloads'
import { Route as SiteSearchRouteImport } from './routes/_site/search'
import { Route as AdminAdminRouteRouteImport } from './routes/admin/_admin/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as SiteSectionIndexRouteImport } from './routes/_site/$section/index'
import { Route as SiteSectionSlugRouteImport } from './routes/_site/$section/$slug'
import { Route as SiteAnnouncementsIndexRouteImport } from './routes/_site/announcements/index'
import { Route as SiteAnnouncementsSlugRouteImport } from './routes/_site/announcements/$slug'
import { Route as SiteDirectoryIndexRouteImport } from './routes/_site/directory/index'
import { Route as SiteDirectoryContactsRouteImport } from './routes/_site/directory/contacts'
import { Route as SiteDirectoryMostVisitedProfilesRouteImport } from './routes/_site/directory/most-visited-profiles'
import { Route as SiteDirectoryMyListingRouteImport } from './routes/_site/directory/my-listing'
import { Route as SiteDirectorySearchRouteImport } from './routes/_site/directory/search'
import { Route as SiteEventsIndexRouteImport } from './routes/_site/events/index'
import { Route as SiteEventsSlugRouteImport } from './routes/_site/events/$slug'
import { Route as SiteNewsIndexRouteImport } from './routes/_site/news/index'
import { Route as SiteNewsSlugRouteImport } from './routes/_site/news/$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminAccountRouteImport } from './routes/admin/_admin/account'
import { Route as AdminAdminActivityRouteImport } from './routes/admin/_admin/activity'
import { Route as AdminAdminDirectoryRouteImport } from './routes/admin/_admin/directory'
import { Route as AdminAdminDirectoryListingsRouteImport } from './routes/admin/_admin/directory-listings'
import { Route as AdminAdminDocumentsRouteImport } from './routes/admin/_admin/documents'
import { Route as AdminAdminMediaRouteImport } from './routes/admin/_admin/media'
import { Route as AdminAdminMessagesRouteImport } from './routes/admin/_admin/messages'
import { Route as AdminAdminPeopleRouteImport } from './routes/admin/_admin/people'
import { Route as AdminAdminSettingsRouteImport } from './routes/admin/_admin/settings'
import { Route as AdminAdminSpotlightsRouteImport } from './routes/admin/_admin/spotlights'
import { Route as AdminAdminUsersRouteImport } from './routes/admin/_admin/users'
import { Route as SiteAcademicsDepartmentsSlugRouteImport } from './routes/_site/academics/departments/$slug'
import { Route as SiteAcademicsUnitsSlugRouteImport } from './routes/_site/academics/units/$slug'
import { Route as SiteDirectoryDSlugRouteImport } from './routes/_site/directory/d/$slug'
import { Route as SiteDirectoryPSlugRouteImport } from './routes/_site/directory/p/$slug'
import { Route as AdminAdminDepartmentsIndexRouteImport } from './routes/admin/_admin/departments/index'
import { Route as AdminAdminDepartmentsDepartmentIdRouteImport } from './routes/admin/_admin/departments/$departmentId'
import { Route as AdminAdminPagesIndexRouteImport } from './routes/admin/_admin/pages/index'
import { Route as AdminAdminPagesPageIdRouteImport } from './routes/admin/_admin/pages/$pageId'
import { Route as AdminAdminPostsIndexRouteImport } from './routes/admin/_admin/posts/index'
import { Route as AdminAdminPostsPostIdRouteImport } from './routes/admin/_admin/posts/$postId'
import { Route as SiteDirectoryDListCategoryRouteImport } from './routes/_site/directory/d/list/$category'

const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteDirectoryRouteRoute = SiteDirectoryRouteRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteDownloadsRoute = SiteDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteSearchRoute = SiteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSectionIndexRoute = SiteSectionIndexRouteImport.update({
  id: '/$section/',
  path: '/$section/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteSectionSlugRoute = SiteSectionSlugRouteImport.update({
  id: '/$section/$slug',
  path: '/$section/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAnnouncementsIndexRoute = SiteAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteAnnouncementsSlugRoute = SiteAnnouncementsSlugRouteImport.update({
  id: '/announcements/$slug',
  path: '/announcements/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteDirectoryIndexRoute = SiteDirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteDirectoryRouteRoute,
} as any)
const SiteDirectoryContactsRoute = SiteDirectoryContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => SiteDirectoryRouteRoute,
} as any)
const SiteDirectoryMostVisitedProfilesRoute =
  SiteDirectoryMostVisitedProfilesRouteImport.update({
    id: '/most-visited-profiles',
    path: '/most-visited-profiles',
    getParentRoute: () => SiteDirectoryRouteRoute,
  } as any)
const SiteDirectoryMyListingRoute = SiteDirectoryMyListingRouteImport.update({
  id: '/my-listing',
  path: '/my-listing',
  getParentRoute: () => SiteDirectoryRouteRoute,
} as any)
const SiteDirectorySearchRoute = SiteDirectorySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteDirectoryRouteRoute,
} as any)
const SiteEventsIndexRoute = SiteEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteEventsSlugRoute = SiteEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteNewsIndexRoute = SiteNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteNewsSlugRoute = SiteNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminAccountRoute = AdminAdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminActivityRoute = AdminAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminDirectoryRoute = AdminAdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminDirectoryListingsRoute =
  AdminAdminDirectoryListingsRouteImport.update({
    id: '/directory-listings',
    path: '/directory-listings',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminDocumentsRoute = AdminAdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminMediaRoute = AdminAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminPeopleRoute = AdminAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminSpotlightsRoute = AdminAdminSpotlightsRouteImport.update({
  id: '/spotlights',
  path: '/spotlights',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const SiteAcademicsDepartmentsSlugRoute =
  SiteAcademicsDepartmentsSlugRouteImport.update({
    id: '/academics/departments/$slug',
    path: '/academics/departments/$slug',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteAcademicsUnitsSlugRoute = SiteAcademicsUnitsSlugRouteImport.update({
  id: '/academics/units/$slug',
  path: '/academics/units/$slug',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteDirectoryDSlugRoute = SiteDirectoryDSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => SiteDirectoryRouteRoute,
} as any)
const SiteDirectoryPSlugRoute = SiteDirectoryPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => SiteDirectoryRouteRoute,
} as any)
const AdminAdminDepartmentsIndexRoute =
  AdminAdminDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminDepartmentsDepartmentIdRoute =
  AdminAdminDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => AdminAdminRouteRoute,
  } as any)
const AdminAdminPagesIndexRoute = AdminAdminPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminPagesPageIdRoute = AdminAdminPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminPostsIndexRoute = AdminAdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminPostsPostIdRoute = AdminAdminPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const SiteDirectoryDListCategoryRoute =
  SiteDirectoryDListCategoryRouteImport.update({
    id: '/d/list/$category',
    path: '/d/list/$category',
    getParentRoute: () => SiteDirectoryRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/directory': typeof SiteDirectoryRouteRouteWithChildren
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/downloads': typeof SiteDownloadsRoute
  '/search': typeof SiteSearchRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/$section/$slug': typeof SiteSectionSlugRoute
  '/announcements/$slug': typeof SiteAnnouncementsSlugRoute
  '/directory/contacts': typeof SiteDirectoryContactsRoute
  '/directory/most-visited-profiles': typeof SiteDirectoryMostVisitedProfilesRoute
  '/directory/my-listing': typeof SiteDirectoryMyListingRoute
  '/directory/search': typeof SiteDirectorySearchRoute
  '/events/$slug': typeof SiteEventsSlugRoute
  '/news/$slug': typeof SiteNewsSlugRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/activity': typeof AdminAdminActivityRoute
  '/admin/directory': typeof AdminAdminDirectoryRoute
  '/admin/directory-listings': typeof AdminAdminDirectoryListingsRoute
  '/admin/documents': typeof AdminAdminDocumentsRoute
  '/admin/media': typeof AdminAdminMediaRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/people': typeof AdminAdminPeopleRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/spotlights': typeof AdminAdminSpotlightsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/$section/': typeof SiteSectionIndexRoute
  '/announcements/': typeof SiteAnnouncementsIndexRoute
  '/directory/': typeof SiteDirectoryIndexRoute
  '/events/': typeof SiteEventsIndexRoute
  '/news/': typeof SiteNewsIndexRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/academics/departments/$slug': typeof SiteAcademicsDepartmentsSlugRoute
  '/academics/units/$slug': typeof SiteAcademicsUnitsSlugRoute
  '/directory/d/$slug': typeof SiteDirectoryDSlugRoute
  '/directory/p/$slug': typeof SiteDirectoryPSlugRoute
  '/admin/departments/$departmentId': typeof AdminAdminDepartmentsDepartmentIdRoute
  '/admin/pages/$pageId': typeof AdminAdminPagesPageIdRoute
  '/admin/posts/$postId': typeof AdminAdminPostsPostIdRoute
  '/admin/departments/': typeof AdminAdminDepartmentsIndexRoute
  '/admin/pages/': typeof AdminAdminPagesIndexRoute
  '/admin/posts/': typeof AdminAdminPostsIndexRoute
  '/directory/d/list/$category': typeof SiteDirectoryDListCategoryRoute
}
export interface FileRoutesByTo {
  '/downloads': typeof SiteDownloadsRoute
  '/search': typeof SiteSearchRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof SiteIndexRoute
  '/$section/$slug': typeof SiteSectionSlugRoute
  '/announcements/$slug': typeof SiteAnnouncementsSlugRoute
  '/directory/contacts': typeof SiteDirectoryContactsRoute
  '/directory/most-visited-profiles': typeof SiteDirectoryMostVisitedProfilesRoute
  '/directory/my-listing': typeof SiteDirectoryMyListingRoute
  '/directory/search': typeof SiteDirectorySearchRoute
  '/events/$slug': typeof SiteEventsSlugRoute
  '/news/$slug': typeof SiteNewsSlugRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/activity': typeof AdminAdminActivityRoute
  '/admin/directory': typeof AdminAdminDirectoryRoute
  '/admin/directory-listings': typeof AdminAdminDirectoryListingsRoute
  '/admin/documents': typeof AdminAdminDocumentsRoute
  '/admin/media': typeof AdminAdminMediaRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/people': typeof AdminAdminPeopleRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/spotlights': typeof AdminAdminSpotlightsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/$section': typeof SiteSectionIndexRoute
  '/announcements': typeof SiteAnnouncementsIndexRoute
  '/directory': typeof SiteDirectoryIndexRoute
  '/events': typeof SiteEventsIndexRoute
  '/news': typeof SiteNewsIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/academics/departments/$slug': typeof SiteAcademicsDepartmentsSlugRoute
  '/academics/units/$slug': typeof SiteAcademicsUnitsSlugRoute
  '/directory/d/$slug': typeof SiteDirectoryDSlugRoute
  '/directory/p/$slug': typeof SiteDirectoryPSlugRoute
  '/admin/departments/$departmentId': typeof AdminAdminDepartmentsDepartmentIdRoute
  '/admin/pages/$pageId': typeof AdminAdminPagesPageIdRoute
  '/admin/posts/$postId': typeof AdminAdminPostsPostIdRoute
  '/admin/departments': typeof AdminAdminDepartmentsIndexRoute
  '/admin/pages': typeof AdminAdminPagesIndexRoute
  '/admin/posts': typeof AdminAdminPostsIndexRoute
  '/directory/d/list/$category': typeof SiteDirectoryDListCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/_site/directory': typeof SiteDirectoryRouteRouteWithChildren
  '/admin/_admin': typeof AdminAdminRouteRouteWithChildren
  '/_site/downloads': typeof SiteDownloadsRoute
  '/_site/search': typeof SiteSearchRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/$section/$slug': typeof SiteSectionSlugRoute
  '/_site/announcements/$slug': typeof SiteAnnouncementsSlugRoute
  '/_site/directory/contacts': typeof SiteDirectoryContactsRoute
  '/_site/directory/most-visited-profiles': typeof SiteDirectoryMostVisitedProfilesRoute
  '/_site/directory/my-listing': typeof SiteDirectoryMyListingRoute
  '/_site/directory/search': typeof SiteDirectorySearchRoute
  '/_site/events/$slug': typeof SiteEventsSlugRoute
  '/_site/news/$slug': typeof SiteNewsSlugRoute
  '/admin/_admin/account': typeof AdminAdminAccountRoute
  '/admin/_admin/activity': typeof AdminAdminActivityRoute
  '/admin/_admin/directory': typeof AdminAdminDirectoryRoute
  '/admin/_admin/directory-listings': typeof AdminAdminDirectoryListingsRoute
  '/admin/_admin/documents': typeof AdminAdminDocumentsRoute
  '/admin/_admin/media': typeof AdminAdminMediaRoute
  '/admin/_admin/messages': typeof AdminAdminMessagesRoute
  '/admin/_admin/people': typeof AdminAdminPeopleRoute
  '/admin/_admin/settings': typeof AdminAdminSettingsRoute
  '/admin/_admin/spotlights': typeof AdminAdminSpotlightsRoute
  '/admin/_admin/users': typeof AdminAdminUsersRoute
  '/_site/$section/': typeof SiteSectionIndexRoute
  '/_site/announcements/': typeof SiteAnnouncementsIndexRoute
  '/_site/directory/': typeof SiteDirectoryIndexRoute
  '/_site/events/': typeof SiteEventsIndexRoute
  '/_site/news/': typeof SiteNewsIndexRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/_site/academics/departments/$slug': typeof SiteAcademicsDepartmentsSlugRoute
  '/_site/academics/units/$slug': typeof SiteAcademicsUnitsSlugRoute
  '/_site/directory/d/$slug': typeof SiteDirectoryDSlugRoute
  '/_site/directory/p/$slug': typeof SiteDirectoryPSlugRoute
  '/admin/_admin/departments/$departmentId': typeof AdminAdminDepartmentsDepartmentIdRoute
  '/admin/_admin/pages/$pageId': typeof AdminAdminPagesPageIdRoute
  '/admin/_admin/posts/$postId': typeof AdminAdminPostsPostIdRoute
  '/admin/_admin/departments/': typeof AdminAdminDepartmentsIndexRoute
  '/admin/_admin/pages/': typeof AdminAdminPagesIndexRoute
  '/admin/_admin/posts/': typeof AdminAdminPostsIndexRoute
  '/_site/directory/d/list/$category': typeof SiteDirectoryDListCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/directory'
    | '/admin'
    | '/downloads'
    | '/search'
    | '/admin/login'
    | '/api/$'
    | '/$section/$slug'
    | '/announcements/$slug'
    | '/directory/contacts'
    | '/directory/most-visited-profiles'
    | '/directory/my-listing'
    | '/directory/search'
    | '/events/$slug'
    | '/news/$slug'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/directory'
    | '/admin/directory-listings'
    | '/admin/documents'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/people'
    | '/admin/settings'
    | '/admin/spotlights'
    | '/admin/users'
    | '/$section/'
    | '/announcements/'
    | '/directory/'
    | '/events/'
    | '/news/'
    | '/admin/'
    | '/academics/departments/$slug'
    | '/academics/units/$slug'
    | '/directory/d/$slug'
    | '/directory/p/$slug'
    | '/admin/departments/$departmentId'
    | '/admin/pages/$pageId'
    | '/admin/posts/$postId'
    | '/admin/departments/'
    | '/admin/pages/'
    | '/admin/posts/'
    | '/directory/d/list/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/downloads'
    | '/search'
    | '/admin/login'
    | '/api/$'
    | '/'
    | '/$section/$slug'
    | '/announcements/$slug'
    | '/directory/contacts'
    | '/directory/most-visited-profiles'
    | '/directory/my-listing'
    | '/directory/search'
    | '/events/$slug'
    | '/news/$slug'
    | '/admin/account'
    | '/admin/activity'
    | '/admin/directory'
    | '/admin/directory-listings'
    | '/admin/documents'
    | '/admin/media'
    | '/admin/messages'
    | '/admin/people'
    | '/admin/settings'
    | '/admin/spotlights'
    | '/admin/users'
    | '/$section'
    | '/announcements'
    | '/directory'
    | '/events'
    | '/news'
    | '/admin'
    | '/academics/departments/$slug'
    | '/academics/units/$slug'
    | '/directory/d/$slug'
    | '/directory/p/$slug'
    | '/admin/departments/$departmentId'
    | '/admin/pages/$pageId'
    | '/admin/posts/$postId'
    | '/admin/departments'
    | '/admin/pages'
    | '/admin/posts'
    | '/directory/d/list/$category'
  id:
    | '__root__'
    | '/_site'
    | '/_site/directory'
    | '/admin/_admin'
    | '/_site/downloads'
    | '/_site/search'
    | '/admin/login'
    | '/api/$'
    | '/_site/'
    | '/_site/$section/$slug'
    | '/_site/announcements/$slug'
    | '/_site/directory/contacts'
    | '/_site/directory/most-visited-profiles'
    | '/_site/directory/my-listing'
    | '/_site/directory/search'
    | '/_site/events/$slug'
    | '/_site/news/$slug'
    | '/admin/_admin/account'
    | '/admin/_admin/activity'
    | '/admin/_admin/directory'
    | '/admin/_admin/directory-listings'
    | '/admin/_admin/documents'
    | '/admin/_admin/media'
    | '/admin/_admin/messages'
    | '/admin/_admin/people'
    | '/admin/_admin/settings'
    | '/admin/_admin/spotlights'
    | '/admin/_admin/users'
    | '/_site/$section/'
    | '/_site/announcements/'
    | '/_site/directory/'
    | '/_site/events/'
    | '/_site/news/'
    | '/admin/_admin/'
    | '/_site/academics/departments/$slug'
    | '/_site/academics/units/$slug'
    | '/_site/directory/d/$slug'
    | '/_site/directory/p/$slug'
    | '/admin/_admin/departments/$departmentId'
    | '/admin/_admin/pages/$pageId'
    | '/admin/_admin/posts/$postId'
    | '/admin/_admin/departments/'
    | '/admin/_admin/pages/'
    | '/admin/_admin/posts/'
    | '/_site/directory/d/list/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/directory': {
      id: '/_site/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof SiteDirectoryRouteRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/downloads': {
      id: '/_site/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof SiteDownloadsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/search': {
      id: '/_site/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SiteSearchRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/$section/': {
      id: '/_site/$section/'
      path: '/$section'
      fullPath: '/$section/'
      preLoaderRoute: typeof SiteSectionIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/$section/$slug': {
      id: '/_site/$section/$slug'
      path: '/$section/$slug'
      fullPath: '/$section/$slug'
      preLoaderRoute: typeof SiteSectionSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/announcements/': {
      id: '/_site/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof SiteAnnouncementsIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/announcements/$slug': {
      id: '/_site/announcements/$slug'
      path: '/announcements/$slug'
      fullPath: '/announcements/$slug'
      preLoaderRoute: typeof SiteAnnouncementsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/directory/': {
      id: '/_site/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof SiteDirectoryIndexRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
    '/_site/directory/contacts': {
      id: '/_site/directory/contacts'
      path: '/contacts'
      fullPath: '/directory/contacts'
      preLoaderRoute: typeof SiteDirectoryContactsRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
    '/_site/directory/most-visited-profiles': {
      id: '/_site/directory/most-visited-profiles'
      path: '/most-visited-profiles'
      fullPath: '/directory/most-visited-profiles'
      preLoaderRoute: typeof SiteDirectoryMostVisitedProfilesRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
    '/_site/directory/my-listing': {
      id: '/_site/directory/my-listing'
      path: '/my-listing'
      fullPath: '/directory/my-listing'
      preLoaderRoute: typeof SiteDirectoryMyListingRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
    '/_site/directory/search': {
      id: '/_site/directory/search'
      path: '/search'
      fullPath: '/directory/search'
      preLoaderRoute: typeof SiteDirectorySearchRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
    '/_site/events/': {
      id: '/_site/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof SiteEventsIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/events/$slug': {
      id: '/_site/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof SiteEventsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/news/': {
      id: '/_site/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof SiteNewsIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/news/$slug': {
      id: '/_site/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof SiteNewsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/account': {
      id: '/admin/_admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAdminAccountRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/activity': {
      id: '/admin/_admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminAdminActivityRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/directory': {
      id: '/admin/_admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminAdminDirectoryRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/directory-listings': {
      id: '/admin/_admin/directory-listings'
      path: '/directory-listings'
      fullPath: '/admin/directory-listings'
      preLoaderRoute: typeof AdminAdminDirectoryListingsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/documents': {
      id: '/admin/_admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminAdminDocumentsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/media': {
      id: '/admin/_admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminAdminMediaRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/messages': {
      id: '/admin/_admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/people': {
      id: '/admin/_admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminAdminPeopleRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/settings': {
      id: '/admin/_admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/spotlights': {
      id: '/admin/_admin/spotlights'
      path: '/spotlights'
      fullPath: '/admin/spotlights'
      preLoaderRoute: typeof AdminAdminSpotlightsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/users': {
      id: '/admin/_admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_site/academics/departments/$slug': {
      id: '/_site/academics/departments/$slug'
      path: '/academics/departments/$slug'
      fullPath: '/academics/departments/$slug'
      preLoaderRoute: typeof SiteAcademicsDepartmentsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/academics/units/$slug': {
      id: '/_site/academics/units/$slug'
      path: '/academics/units/$slug'
      fullPath: '/academics/units/$slug'
      preLoaderRoute: typeof SiteAcademicsUnitsSlugRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/directory/d/$slug': {
      id: '/_site/directory/d/$slug'
      path: '/d/$slug'
      fullPath: '/directory/d/$slug'
      preLoaderRoute: typeof SiteDirectoryDSlugRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
    '/_site/directory/p/$slug': {
      id: '/_site/directory/p/$slug'
      path: '/p/$slug'
      fullPath: '/directory/p/$slug'
      preLoaderRoute: typeof SiteDirectoryPSlugRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
    '/admin/_admin/departments/': {
      id: '/admin/_admin/departments/'
      path: '/departments'
      fullPath: '/admin/departments/'
      preLoaderRoute: typeof AdminAdminDepartmentsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/departments/$departmentId': {
      id: '/admin/_admin/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/admin/departments/$departmentId'
      preLoaderRoute: typeof AdminAdminDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/pages/': {
      id: '/admin/_admin/pages/'
      path: '/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AdminAdminPagesIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/pages/$pageId': {
      id: '/admin/_admin/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminAdminPagesPageIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/posts/': {
      id: '/admin/_admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminAdminPostsIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/posts/$postId': {
      id: '/admin/_admin/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/admin/posts/$postId'
      preLoaderRoute: typeof AdminAdminPostsPostIdRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_site/directory/d/list/$category': {
      id: '/_site/directory/d/list/$category'
      path: '/d/list/$category'
      fullPath: '/directory/d/list/$category'
      preLoaderRoute: typeof SiteDirectoryDListCategoryRouteImport
      parentRoute: typeof SiteDirectoryRouteRoute
    }
  }
}

interface SiteDirectoryRouteRouteChildren {
  SiteDirectoryContactsRoute: typeof SiteDirectoryContactsRoute
  SiteDirectoryMostVisitedProfilesRoute: typeof SiteDirectoryMostVisitedProfilesRoute
  SiteDirectoryMyListingRoute: typeof SiteDirectoryMyListingRoute
  SiteDirectorySearchRoute: typeof SiteDirectorySearchRoute
  SiteDirectoryIndexRoute: typeof SiteDirectoryIndexRoute
  SiteDirectoryDSlugRoute: typeof SiteDirectoryDSlugRoute
  SiteDirectoryPSlugRoute: typeof SiteDirectoryPSlugRoute
  SiteDirectoryDListCategoryRoute: typeof SiteDirectoryDListCategoryRoute
}

const SiteDirectoryRouteRouteChildren: SiteDirectoryRouteRouteChildren = {
  SiteDirectoryContactsRoute: SiteDirectoryContactsRoute,
  SiteDirectoryMostVisitedProfilesRoute: SiteDirectoryMostVisitedProfilesRoute,
  SiteDirectoryMyListingRoute: SiteDirectoryMyListingRoute,
  SiteDirectorySearchRoute: SiteDirectorySearchRoute,
  SiteDirectoryIndexRoute: SiteDirectoryIndexRoute,
  SiteDirectoryDSlugRoute: SiteDirectoryDSlugRoute,
  SiteDirectoryPSlugRoute: SiteDirectoryPSlugRoute,
  SiteDirectoryDListCategoryRoute: SiteDirectoryDListCategoryRoute,
}

const SiteDirectoryRouteRouteWithChildren =
  SiteDirectoryRouteRoute._addFileChildren(SiteDirectoryRouteRouteChildren)

interface SiteRouteRouteChildren {
  SiteDirectoryRouteRoute: typeof SiteDirectoryRouteRouteWithChildren
  SiteDownloadsRoute: typeof SiteDownloadsRoute
  SiteSearchRoute: typeof SiteSearchRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteSectionSlugRoute: typeof SiteSectionSlugRoute
  SiteAnnouncementsSlugRoute: typeof SiteAnnouncementsSlugRoute
  SiteEventsSlugRoute: typeof SiteEventsSlugRoute
  SiteNewsSlugRoute: typeof SiteNewsSlugRoute
  SiteSectionIndexRoute: typeof SiteSectionIndexRoute
  SiteAnnouncementsIndexRoute: typeof SiteAnnouncementsIndexRoute
  SiteEventsIndexRoute: typeof SiteEventsIndexRoute
  SiteNewsIndexRoute: typeof SiteNewsIndexRoute
  SiteAcademicsDepartmentsSlugRoute: typeof SiteAcademicsDepartmentsSlugRoute
  SiteAcademicsUnitsSlugRoute: typeof SiteAcademicsUnitsSlugRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteDirectoryRouteRoute: SiteDirectoryRouteRouteWithChildren,
  SiteDownloadsRoute: SiteDownloadsRoute,
  SiteSearchRoute: SiteSearchRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteSectionSlugRoute: SiteSectionSlugRoute,
  SiteAnnouncementsSlugRoute: SiteAnnouncementsSlugRoute,
  SiteEventsSlugRoute: SiteEventsSlugRoute,
  SiteNewsSlugRoute: SiteNewsSlugRoute,
  SiteSectionIndexRoute: SiteSectionIndexRoute,
  SiteAnnouncementsIndexRoute: SiteAnnouncementsIndexRoute,
  SiteEventsIndexRoute: SiteEventsIndexRoute,
  SiteNewsIndexRoute: SiteNewsIndexRoute,
  SiteAcademicsDepartmentsSlugRoute: SiteAcademicsDepartmentsSlugRoute,
  SiteAcademicsUnitsSlugRoute: SiteAcademicsUnitsSlugRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

interface AdminAdminRouteRouteChildren {
  AdminAdminAccountRoute: typeof AdminAdminAccountRoute
  AdminAdminActivityRoute: typeof AdminAdminActivityRoute
  AdminAdminDirectoryRoute: typeof AdminAdminDirectoryRoute
  AdminAdminDirectoryListingsRoute: typeof AdminAdminDirectoryListingsRoute
  AdminAdminDocumentsRoute: typeof AdminAdminDocumentsRoute
  AdminAdminMediaRoute: typeof AdminAdminMediaRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminPeopleRoute: typeof AdminAdminPeopleRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSpotlightsRoute: typeof AdminAdminSpotlightsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminDepartmentsDepartmentIdRoute: typeof AdminAdminDepartmentsDepartmentIdRoute
  AdminAdminPagesPageIdRoute: typeof AdminAdminPagesPageIdRoute
  AdminAdminPostsPostIdRoute: typeof AdminAdminPostsPostIdRoute
  AdminAdminDepartmentsIndexRoute: typeof AdminAdminDepartmentsIndexRoute
  AdminAdminPagesIndexRoute: typeof AdminAdminPagesIndexRoute
  AdminAdminPostsIndexRoute: typeof AdminAdminPostsIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminAccountRoute: AdminAdminAccountRoute,
  AdminAdminActivityRoute: AdminAdminActivityRoute,
  AdminAdminDirectoryRoute: AdminAdminDirectoryRoute,
  AdminAdminDirectoryListingsRoute: AdminAdminDirectoryListingsRoute,
  AdminAdminDocumentsRoute: AdminAdminDocumentsRoute,
  AdminAdminMediaRoute: AdminAdminMediaRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminPeopleRoute: AdminAdminPeopleRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSpotlightsRoute: AdminAdminSpotlightsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminDepartmentsDepartmentIdRoute:
    AdminAdminDepartmentsDepartmentIdRoute,
  AdminAdminPagesPageIdRoute: AdminAdminPagesPageIdRoute,
  AdminAdminPostsPostIdRoute: AdminAdminPostsPostIdRoute,
  AdminAdminDepartmentsIndexRoute: AdminAdminDepartmentsIndexRoute,
  AdminAdminPagesIndexRoute: AdminAdminPagesIndexRoute,
  AdminAdminPostsIndexRoute: AdminAdminPostsIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
