CREATE TABLE IF NOT EXISTS posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type ENUM('news', 'event', 'announcement') NOT NULL,
  slug VARCHAR(200) NOT NULL,
  title VARCHAR(255) NOT NULL,
  excerpt VARCHAR(600) NULL,
  body MEDIUMTEXT NULL,
  cover_image_url VARCHAR(700) NULL,
  category VARCHAR(80) NULL,
  tags JSON NULL,
  is_featured TINYINT(1) NOT NULL DEFAULT 0,
  is_pinned TINYINT(1) NOT NULL DEFAULT 0,
  status ENUM('draft', 'published', 'archived') NOT NULL DEFAULT 'draft',
  published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  event_start DATETIME NULL,
  event_end DATETIME NULL,
  venue VARCHAR(255) NULL,
  registration_url VARCHAR(500) NULL,
  attachment_url VARCHAR(700) NULL,
  expires_on DATE NULL,
  view_count INT UNSIGNED NOT NULL DEFAULT 0,
  author_id INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_posts_type_slug (type, slug),
  KEY idx_posts_listing (type, status, published_at),
  KEY idx_posts_events (type, status, event_start),
  CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES admins (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_posts_updated_by FOREIGN KEY (updated_by) REFERENCES admins (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
