CREATE TABLE IF NOT EXISTS spotlights (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  eyebrow VARCHAR(60) NULL,
  title VARCHAR(200) NOT NULL,
  caption VARCHAR(500) NULL,
  image_url VARCHAR(700) NOT NULL,
  cta_label VARCHAR(60) NULL,
  cta_url VARCHAR(500) NULL,
  starts_on DATE NULL,
  ends_on DATE NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_spotlights_active (is_active, sort_order),
  CONSTRAINT fk_spotlights_created_by FOREIGN KEY (created_by) REFERENCES admins (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
